[package]
name = "mcp-attr-example-cargo-metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
mcp-attr = "0.0.2"
tokio = { version = "1.44.0", features = ["full"] }
cargo_metadata = "0.18.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
